### ISSUE TITLE
how to ensure time synchronization In the cluster environment

### ISSUE THREAD

**Issue by zhaohuatai** [sony/sonyflake#2]
how to ensure time synchronization In the cluster environment,  have any good solution

**Comment by YoshiyukiMineo** [comment]
We use ntpd in slew mode so that the local clocks never move backwards.
The local clocks should be synced once before starting Sonyflake and periodically after starting it.
If the difference between a local clock and the reference clock is larger than some threshold (a few minutes or so), you should stop Sonyflake (But I think it is a very rare case).

**Comment by prologic** [comment]
Q: How is this library considered "distributed"? Where's the distributed part?

**Comment by deanhiller** [comment]
@zhaohuatai why do you need 'good' time sync.  since the id is made up of node id, that nodes time is independent of another nodes time.  IF you restart a server, it takes so long, that a node of id=1 won't re-use existing times until the time sync is way way off. Therefore, you do not need the time sync to be good.

@prologic it's distributed in that we need a globally unique id on a distributed cluster and this library does that job.  first by node id, then timestamp then on that same server if both of those match, by the 3rd field generating a completely globally unique number (as long as all your node ids are different in different data centers too)

The clock skew can be no greater than the time it takes to restart a node I believe.

**Comment by prologic** [comment]
@deanhiller So this is using some kind of custom consensus? I didn't see any use of Raft or similar?

**Comment by titpetric** [comment]
@prologic there is no consensus, nothing is shared between sonyflake instances. Each individual instance of an application that uses sonyflake is an independent worker that can generate sonyflake IDs for that particular host/SERVER_ID.

**Comment by claymodel** [comment]
It would be great if you provide the unique ID spec.
If there is a configuration so that we can embed the server id.
thanks.
