### ISSUE TITLE
Is it practical to implement sonyflake in RDBMS like MySQL, Postgres?

### ISSUE THREAD

**Issue by AmreeshTyagi** [sony/sonyflake#21]
Just curious to know, how practical is it to limit generation of 2^8 (256) unique IDs per 10ms on databases.
Can someone please explain me with example like if I have 4GB RAM to 16GB RAM database instance, how many insert load I can expect to be handled by that server? 

It will help me use sonyflake as id generation at database level.

**Comment by ZenLiuCN** [comment]
10ms/256->just means 1s->256*10->2560 insert will be insert into a database.There is nothing about you database.but how many unique data you want to put. In a test conditon, MySQL in a Docker container (1G) could insert about 1M Unique key in 1s.

**Comment by BlameOmar** [comment]
> 10ms/256->just means 1s->256*10->2560 insert will be insert into a database.There is nothing about you database.but how many unique data you want to put. In a test conditon, MySQL in a Docker container (1G) could insert about 1M Unique key in 1s.

1s/10ms = 100, so that should be 256*10 = 25600 ids per second per node. That's a fair amount of load per node, but not an amazing amount either. It is probably the perfect size for running hundreds/thousands of instances on shared physical hosts in a cloud environment.

In general, ID generation is not tied to the persistence layer, so the sequence number limit doesn't really matter. The persistence layer simply needs to scale for the total load across all nodes. If you actually have 1.68 billion QPS, you need much more than 1 database server.

I wonder if you're trying to implement snowflake in the persistence layer itself (like UUID support in PostgreSQL), @AmreeshTyagi. The design of sonyflake (and other snowflake derivatives) is such that this is unnecessary and I recommend that you not do that unless you absolutely must. In that case, you might want to use more bits for the per-thread sequence number and less for the node id if you require more QPS on the database host.

**Comment by AmreeshTyagi** [comment]
>I recommend that you not do that unless you absolutely must. In that case, you might want to use more bits for the per-thread sequence number and less for the node id if you require more QPS on the database host.
Exactly, that's why I have created my own derivative name as [goldflake](https://github.com/AmreeshTyagi/goldflake) for applications & [goldflake-pg](https://github.com/AmreeshTyagi/goldflake-pg) for postgresql database, which seems balanced approach to me for most of the use cases at present.
